import Image from "next/image";
import { SiteHeader } from "@/components/navigation/SiteHeader";
import { SiteFooter } from "@/components/navigation/SiteFooter";
import { Button } from "@/components/ui/Button";
import { ConceptLabel } from "@/components/ui/ConceptLabel";

type Variant = "portfolio" | "attention" | "field" | "handover";
type Props = { eyebrow: string; headline: string; standfirst: string; variant: Variant; points: { title: string; body: string }[]; image?: { src: string; alt: string }; qualification?: string };

function DataVisual({ variant }: { variant: "portfolio" | "attention" }) {
  if (variant === "portfolio") return <div className="grid grid-cols-2 gap-px border border-hairline bg-hairline" role="img" aria-label="Conceptual portfolio view showing four building records with distinct current states.">{["Harbour Court · 3 open", "Marlowe House · review", "Ash Yard · 1 priority", "Elm Lodge · current"].map((item, index) => <div key={item} className="bg-white p-5"><span className={`block h-2 w-2 rounded-full ${index === 2 ? "bg-ember" : index === 3 ? "bg-verified" : "bg-amber"}`} /><p className="mt-5 font-mono text-xs text-navy">{item}</p></div>)}</div>;
  return <div className="border-y border-hairline" role="img" aria-label="Conceptual attention register ordered by priority, ownership and next action.">{[["P1", "Awaiting client decision"], ["P2", "Evidence under review"], ["P4", "Action assigned"]].map(([priority, state], index) => <div key={priority} className="grid grid-cols-[52px_1fr_auto] items-center gap-4 border-b border-hairline px-2 py-5 last:border-b-0"><span className={`font-mono text-sm font-semibold ${index === 0 ? "text-ember" : "text-navy"}`}>{priority}</span><span className="text-sm text-navy">{state}</span><span className="font-mono text-[10px] text-text-secondary uppercase">owner visible</span></div>)}</div>;
}

export function RoleSolutionPage({ eyebrow, headline, standfirst, variant, points, image, qualification }: Props) {
  const photographic = variant === "field" || variant === "handover";
  return <><SiteHeader /><main>
    <section className={`${variant === "attention" ? "bg-grey" : variant === "handover" ? "bg-navy" : "bg-white"} px-4 py-16 md:px-16 md:py-24`}><div className={`mx-auto max-w-280 ${photographic ? "grid gap-10 md:grid-cols-[0.9fr_1.1fr] md:items-center" : ""}`}><div className={photographic ? "" : "max-w-3xl"}><p className={`font-mono text-[11px] tracking-[0.12em] uppercase ${variant === "handover" ? "text-ember" : "text-ember-hover"}`}>{eyebrow}</p><h1 className={`mt-4 font-display text-[30px] leading-[1.16] font-bold md:text-[48px] ${variant === "handover" ? "text-white" : "text-navy"}`}>{headline}</h1><p className={`mt-5 max-w-2xl text-base leading-relaxed md:text-lg ${variant === "handover" ? "text-on-navy-secondary" : "text-text-secondary"}`}>{standfirst}</p><Button href="/book-a-demo" className="mt-7">Book a Demo</Button></div>{image ? <figure className="mt-10 md:mt-0"><div className="relative aspect-[16/10] overflow-hidden"><Image src={image.src} alt={image.alt} fill priority sizes="(min-width: 768px) 52vw, 100vw" className="object-cover" /></div><figcaption className={`mt-3 ${variant === "handover" ? "[&_p]:text-on-navy-muted" : ""}`}><ConceptLabel>editorial illustration; no customer or live record shown</ConceptLabel></figcaption></figure> : null}</div></section>
    {!photographic ? <section className="px-4 py-14 md:px-16 md:py-24"><div className="mx-auto grid max-w-280 gap-12 md:grid-cols-[0.8fr_1.2fr] md:items-start"><div><p className="font-mono text-[11px] text-ember-hover uppercase">One record, your operating view</p><h2 className="mt-3 font-display text-2xl font-bold text-navy">The next decision is visible before the next report is due.</h2><div className="mt-4"><ConceptLabel>synthetic names and statuses</ConceptLabel></div></div><DataVisual variant={variant as "portfolio" | "attention"} /></div></section> : null}
    <section className={`${variant === "field" ? "bg-grey" : "bg-white"} px-4 py-14 md:px-16 md:py-24`}><div className="mx-auto max-w-280"><h2 className="font-display text-2xl font-bold text-navy md:text-[34px]">What changes in practice.</h2><ol className={`mt-10 ${variant === "portfolio" ? "border-l-2 border-navy pl-7" : "grid gap-px border border-hairline bg-hairline md:grid-cols-2"}`}>{points.map((point, index) => <li key={point.title} className={variant === "portfolio" ? "relative pb-9 last:pb-0" : "bg-white p-6 md:p-8"}>{variant === "portfolio" ? <span className="absolute top-1 -left-[35px] h-4 w-4 rounded-full border-4 border-white bg-ember" aria-hidden="true" /> : <span className="font-mono text-[11px] text-ember">{String(index + 1).padStart(2, "0")}</span>}<h3 className={`${variant === "portfolio" ? "" : "mt-4"} font-display text-xl font-bold text-navy`}>{point.title}</h3><p className="mt-2 text-[15px] leading-relaxed text-text-secondary">{point.body}</p></li>)}</ol>{qualification ? <p className="mt-8 border-l-2 border-amber pl-4 text-sm leading-relaxed text-text-secondary">{qualification}</p> : null}</div></section>
    <section className="border-t-[3px] border-ember bg-priority px-4 py-14 text-center md:px-16 md:py-20"><h2 className="font-display text-2xl font-bold text-navy">Discuss your operating model with Widian.</h2><Button href="/book-a-demo" className="mt-6">Book a Demo</Button></section>
  </main><SiteFooter /></>;
}
